services:
  # ========================
  # ===== MARIADB ===========
  # ========================
  db:
    image: mariadb:latest
    container_name: questsedges_db
    restart: unless-stopped
    environment:
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
    ports:
      - "${MARIADB_PORT}:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - mariadb_logs:/var/log/mysql
    networks:
      - gamingnet
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    command:
      - --max_connections=1000
      - --default-storage-engine=InnoDB
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  # ========================
  # ===== API ==============
  # ========================
  api:
    image: node:20-alpine
    container_name: questsedges_api
    restart: unless-stopped
    working_dir: /app
    env_file: .env
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"
    volumes:
      - ./dist:/app/dist
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./prisma:/app/prisma
      - api_node_modules:/app/node_modules
    networks:
      - gamingnet
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    command: node dist/index.js

volumes:
  mariadb_data:
    driver: local
  mariadb_logs:
    driver: local
  api_node_modules:
    driver: local

networks:
  gamingnet:
    external: true